apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-platform-config
data:
  postgres_host: "{{ .Values.postgres.host }}"
  postgres_port: "{{ .Values.postgres.port }}"
  redis_host: "{{ .Values.redis.host }}"
  redis_port: "{{ .Values.redis.port }}"
  kafka_bootstrap_servers: "{{ .Values.kafka.bootstrapServers }}"
  mosquitto_host: "{{ .Values.mosquitto.host }}"
  mosquitto_port: "{{ .Values.mosquitto.port }}"
