{{- if and .Values.deviceRegistry.enabled .Values.deviceRegistry.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: device-registry-ingress
  labels:
    {{- include "iot-platform.deviceRegistry.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{ .Values.deviceRegistry.ingress.host }}
    http:
      paths:
      - path: {{ .Values.deviceRegistry.ingress.path }}
        pathType: {{ .Values.deviceRegistry.ingress.pathType }}
        backend:
          service:
            name: device-registry
            port:
              number: {{ .Values.deviceRegistry.service.port }}
{{- end }}
