apiVersion: v1
kind: Secret
metadata:
  name: iot-platform-secret
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
  jwt-secret: {{ .Values.deviceRegistry.env.jwtSecretKey | quote }}
  smtp-password: {{ .Values.alertEngine.env.smtpPassword | quote }}
